### ISSUE TITLE
There are two problems when running MiCall

### ISSUE THREAD

**Issue by Anastasiamiaomiao** [PoonLab/MiCall-Lite#25] opened 2019-09-05 01:50 UTC
Hello, I have two questions ,

1.After adding the file ErrorMetricsOut.bin, the operation error occurs, and the prompt is as shown in the figure:
![ERROR](https://user-images.githubusercontent.com/41099785/64303214-affcf200-cfb9-11e9-9a68-368a54e77389.png)

2.There is no problem when running some .fastq.gz files, but other .fastq.gz files have errors when running remap, the prompts are as follows:
![REMAP](https://user-images.githubusercontent.com/41099785/64303230-be4b0e00-cfb9-11e9-91b9-6149c7217a63.png)

Hope to answer, thank you very much!

**Comment by ArtPoon** [comment] 2019-09-05 01:53
Hi, thanks for trying out MiCall-Lite and reporting this issue!
Can you please let me know what version of Ubuntu you're running, and version of Python?
Are you able to send me the files so that I can try to reproduce the problem?

**Comment by ArtPoon** [comment] 2019-09-05 02:36
Ok, the first error seems to be a bug in `censor_fastq.py` where `'N'` should be prefixed with a `b`.
The second error is more unusual.  Can I ask what you're sequencing?

**Comment by Anastasiamiaomiao** [comment] 2019-09-05 02:52
Hi,
the version of Ubuntu:Ubuntu16.04 LTS;
the version of Python:Python 3.5.2;
The file  is too large and was not uploaded successfully on github.

**Comment by Anastasiamiaomiao** [comment] 2019-09-05 03:01
Current sequencing :
The drug resistance mutations during antiretroviral therapy (ART) discontinuation in AIDS patients starting ART at early stage of National Free ART Program.

**Comment by ArtPoon** [comment] 2019-09-05 03:03
@Anastasiamiaomiao - sorry for the misunderstanding.  I wasn't suggesting that you upload FASTQ files to GitHub, as that would certainly exceed upload limits.  I would have proposed giving you temporary access to one of my servers for an sftp transfer, or I can show you how to extract a short portion of a FASTQ file to send via e-mail.

**Comment by Anastasiamiaomiao** [comment] 2019-09-05 03:10
OK
Please tell me how to extract a short portion of a FASTQ file.
Thanks.

**Comment by ArtPoon** [comment] 2019-09-05 03:12
@Anastasiamiaomiao, can you please run the following commands:
```console
# stream the first 4000 lines of uncompressed FASTQ to new files
gunzip -c /home/zoe/dlty/10_S10_L001_R1_001.fastq.gz | head -n4000 > test1.fastq
gunzip -c /home/zoe/dlty/10_S10_L001_R2_001.fastq.gz | head -n4000 > test2.fastq
```
and then e-mail me (apoon42@uwo.ca) so I can send you a temporary username and password to my server?  Then we can arrange a secure file transfer.  I will also need the `ErrorMetricsOut.bin` file.

**Comment by ArtPoon** [comment] 2019-09-05 03:45
I haven't been able to reproduce the problem with the shortened files.

**Comment by Anastasiamiaomiao** [comment] 2019-09-05 05:35
After the update, I tried to run it. Another error has occurred.

micall -i /home/zoe/dlty/ErrorMetricsOut.bin /home/zoe/dlty/10_S10_L001_R1_001.fastq.gz /home/zoe/dlty/10_S10_L001_R2_001.fastq.gz

MiCall-Lite running sample 10_S10_L001_R1_001...
  Censoring bad tile-cycle combos in FASTQ
Traceback (most recent call last):
  File "/usr/local/bin/micall", line 156, in <module>
    run_sample(args)
  File "/usr/local/bin/micall", line 112, in run_sample
    args = censor_fastqs(args, prefix)
  File "/usr/local/bin/micall", line 95, in censor_fastqs
    use_gzip=not args.unzipped)
  File "/usr/local/lib/python3.5/dist-packages/micall/core/censor_fastq.py", line 88, in censor
    dest.write('#' * bad_count)
  File "/usr/lib/python3.5/gzip.py", line 258, in write
    data = memoryview(data)
TypeError: memoryview: a bytes-like object is required, not 'str'

**Comment by ArtPoon** [comment] 2019-09-05 14:56
Thanks for securely transferring the data.  I've been able to reproduce both errors and am debugging now.

**Comment by ArtPoon** [comment] 2019-09-05 16:29
Ok, I've patched the master branch and made a successful run:
```console
art@orolo:~/git/micall/issue25$ micall -i ErrorMetricsOut.bin 10_S10_L001_R1_001.fastq.gz 10_S10_L001_R2_001.fastq.gz 
MiCall-Lite running sample 10_S10_L001_R1_001...
  Censoring bad tile-cycle combos in FASTQ
  Preliminary map
  Iterative remap
  Generating alignment file
  Generating count files
```

Based on your interop file, this run has some fairly high error rates (colour indicates % error rate in phiX174 control; plot generated using Python and R scripts [published here](https://github.com/PoonLab/courses/tree/master/Cuernavaca/scripts)):
![interop](https://user-images.githubusercontent.com/1109328/64354821-23106380-cfce-11e9-9e57-dcaf7d02f4b7.png)

so you should be cautious about how you interpret these data.  Due to these high error rates, analyzing the FASTQ files triggered a subroutine in MiCall-Lite that had never been properly tested.  I found the bug that caused a `TypeError` exception to be thrown.

Here is a summary of the `nuc.csv` output file:
![coverage](https://user-images.githubusercontent.com/1109328/64360501-9d45e580-cfd8-11e9-95bc-53978d3d8ddb.png)

Can you please pull the latest version from the master branch and try running it on your data?

**Comment by Anastasiamiaomiao** [comment] 2019-09-06 05:15
Thank you, I have been able to run successfully.
However, I still have a question to ask.
1. How to draw a coverage plot with an R script based on file nuc.csv?

**Comment by Anastasiamiaomiao** [comment] 2019-09-06 07:38
2.The command **python3 batch-micall.py /home/zoe/dlty/** does not consider the ErrorMetricsOut.bin file, which location should it be added to?

**Comment by ArtPoon** [comment] 2019-09-06 16:29
> 2.The command **python3 batch-micall.py /home/zoe/dlty/** does not consider the ErrorMetricsOut.bin file, which location should it be added to?

Actually, the `batch-micall.py` script *should* accept the same arguments as `micall`, *i.e.*,
```console
art@orolo:/data/miseq/integrase$ python3 ~/git/micall/bin/batch-micall.py . -i ~/git/micall/issue25/ErrorMetricsOut.bin
Detected 523 gzipped FASTQ files at .
./DR-88-13-2_S180_L001_R1_001.fastq.gz
MiCall-Lite running sample DR-88-13-2_S180_L001_R1_001...
  Censoring bad tile-cycle combos in FASTQ
```

**Comment by ArtPoon** [comment] 2019-09-06 17:15
While working on the `micall` script, I realized that you should be modifying the `--readlen` setting because you're using a reagent kit with slightly longer reads - MiCall defaults to 251 nt.

**Comment by ArtPoon** [comment] 2019-09-06 20:13
Revised master branch, `micall` will now take `--batch` or `-b` argument for batch processing all FASTQ files in user-specified directory.

**Comment by ArtPoon** [comment] 2019-09-08 19:37
Added `coverage.R` script at `micall/utils/`:
```console
Elzar:micall artpoon$ micall/utils/coverage.R examples/Example_S1_L001_R1_001.amino.csv output
```
This generates a PDF file for every seed and region combination in the CSV output.  In the case of this example file, there are three PDFs (for the regions INT, PR and RT, respectively):
![output HIV1B-pol-seed INT](https://user-images.githubusercontent.com/1109328/64493424-48130980-d24e-11e9-98ca-5ae120b87148.png)

This script automatically detects whether you are dealing with nucleotide or amino acid CSV outputs (`*.nuc.csv` or `*.amino.csv`, respectively).

**Closed** 2019-09-08 19:37 UTC
Labels: bug

**Comment by Anastasiamiaomiao** [comment] 2019-09-09 02:19
Ok, Thank you very much!


| |
Miaomiao Li
|
|
miaomiao_ana@163.com
|
签名由网易邮箱大师定制
On 9/7/2019 00:29，Art Poon<notifications@github.com> wrote：

2.The command python3 batch-micall.py /home/zoe/dlty/ does not consider the ErrorMetricsOut.bin file, which location should it be added to?

Actually, the batch-micall.py script should accept the same arguments as micall, i.e.,

art@orolo:/data/miseq/integrase$ python3 ~/git/micall/bin/batch-micall.py . -i ~/git/micall/issue25/ErrorMetricsOut.binDetected 523 gzipped FASTQ files at ../DR-88-13-2_S180_L001_R1_001.fastq.gzMiCall-Lite running sample DR-88-13-2_S180_L001_R1_001...  Censoring bad tile-cycle combos in FASTQ
